
title: My Resume
url: 'http://drthaodao.github.io'
baseurl: '/drthaodao.github.io' #change it according to your repository name



# Profile information
yourname: Thao Dao  ## put your name
title: 'ENT Doctor'  ## your title
location: HoChiMinh City , Vietnam


## Social Profiles
facebook: https://www.facebook.com/thao.dao.790/  ## your facebook account url
twitter: https://twitter.com/ThaoDao76881589  ## your twitter account url
linkedin: https://www.linkedin.com/in/dao-thao-85b3691bb/ ## your linkedin account url




# Update all the sections by editing the files inside _includes folder.
