
title: My Resume
url: 'http://drthaodao.github.io'
baseurl: '/drthaodao.github.io' #change it according to your repository name



# Profile information
yourname: Thao Dao  ## put your name
title: 'ENT Doctor'  ## your title
location: HoChiMinh City , Vietnam


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
